version: '3.8'

services:
  grove-vision-ai:
    image: himax_rabboni
    container_name: himax_rabboni_builder
    volumes:
      - type: bind
        source: ./firmware
        target: /root/firmware
    environment:
      - TZ=Asia/Taipei
    command: tail -f /dev/null
    ports:
      - "2222:22"

